name:       Chiya
version:    '0.1.0.0'
category:   Language
author:     Tosainu
maintainer: tosainu.maple@gmail.com
copyright:  2017 Tosainu
license:    MIT
github:     Tosainu/Chiya
extra-source-files:
  - README.md

ghc-options: -Wall

library:
  source-dirs: src
  dependencies:
    - base >=4.7 && <5
    - mtl

executables:
  chiyac:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - base
      - mtl
      - Chiya

tests:
  Chiya-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - base
      - Chiya
